Solution
mate-academy/qa_cypress_e2e_article_flow pull request #103
Opened 2023-09-21 17:08 UTC by lkvashchuk

2023-09-21 17:23 UTC, closed without merging

2023-09-21 20:41 UTC, yelyzaveta25 approved these changes
I can’t fully check this because we also made changes to the cypress.config.js file, added a command to create an article, but this file is not in this pull request. But I looked at the code and it seems to me that everything is fine, good job!

2023-09-22 12:38 UTC, djtyrf312 requested changes

2023-09-22 12:38 UTC, djtyrf312 commented on cypress/e2e/article.cy.js
> +    cy.login(user.email, user.username, user.password);
![image](https://github.com/mate-academy/qa_cypress_e2e_article_flow/assets/85580286/8772c3f6-a272-4fa4-b280-6543c9f96c78)
this error always appears

2023-09-25 13:37 UTC, Oleksii-Siviolov approved these changes
Well done.